name: terraform apply

on:
    pull_request_review:
      types: [submitted]

env:
    tf_actions_working_dir: ./terraform
jobs:
        creating:
            runs-on: ubuntu-latest
            steps:
                - name: clone 
                  run: |
                  # terraform init
                    # terraform plan
                    # terraform apply

    job2:
    job3: