name: terraform apply

on:
    pull_request_review:
      types: [submitted]

env:
    tf_actions_working_dir: ./terraform
jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
      - name: Checkout
        uses: actions/checkout@v3
      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: ${{ env.tf_actions_working_dir }}
          auto_approve: true